<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="..\AIrhythm.Version.props" />
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Platforms>x86;x64</Platforms>
    <Prefer32Bit>false</Prefer32Bit>
    <RootNamespace>AIrhythm.BasicPlugin</RootNamespace>
    <AssemblyName>AIrhythm.BasicPlugin</AssemblyName>
    <Version>$(AIrhythmVersion)</Version>
    <FileVersion>$(AIrhythmVersion).0</FileVersion>
    <AssemblyVersion>$(AIrhythmVersion).0</AssemblyVersion>
    <InformationalVersion>$(AIrhythmVersion)</InformationalVersion>
    <OutputType>Library</OutputType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Platform)'=='x86'">
    <PlatformTarget>x86</PlatformTarget>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Platform)'=='x64'">
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\TvAIrPlugin\TvAIrPlugin.csproj" Private="false" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="Assets\**\*" />
  </ItemGroup>
</Project>
